###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "firstname": "fname",
    "lastname": "lname",
    "email": "first@email.com",
    "password": "second",
    "dob": "2020-07-07"
}